
[tool.ruff]
exclude = [
    "meld/ui/gladesupport.py",
    "setup_win32.py",
]

select = ["E4", "E7", "E9", "F", "I"]
ignore = ["E741"]

[tool.ruff.isort]
known-first-party = [
    "meld",
]
no-lines-before = [
    "local-folder",
]
order-by-type = true
